### ISSUE TITLE
Add a `.plugin.zsh` file to make it easier to use with frameworks

### ISSUE THREAD

**Issue by unixorn** [zchee/go-zsh-completions#1]
If you add a `.plugin.zsh` file that adds the src directory to `$fpath`, this will be a lot easier to use with zsh plugins. Modern ones like zgen or antigen will be able to automatically clone it and use it, and oh-my-zsh users will just have to clone it into their local plugins directory.

**Comment by zchee** [comment]
@unixorn Hi,
I'm never used oh-my-zsh, What should I create the file? also, that's file is empty is ok?

like:
`go-zsh-completions.plugin.zsh`?
